package com.jpoole.service_novigrad;

import java.util.*;

public class Branch {
    private String id; // id generated by db
    private String address;
    private String phone;
    private double rating;
    private List<String> hours;
    private List<String> services;
    private List<String> openRequests;

    public Branch(){
        this.id="";
        this.address ="";
        this.phone = "";
        this.hours = new ArrayList<String>(4);
        this.services = new ArrayList<String>();
        this.openRequests = new ArrayList<String>();
    }

    public String getId(){
        return id;
    }
    public void setId(String id){
        this.id = id;
    }

    public String getAddress(){ return this.address; }
    public void setAddress(String address){
        this.address = address;
    }

    public String getPhone(){ return this.phone; }
    public void setPhone(String phone) { this.phone = phone; }

    public double getRating(){ return this.rating; }
    public void setRating(double rating){ this.rating = rating; }

    //Methods for working with branch hours
    public List<String> getHours(){ return this.hours; }
    public void setHours(List<String> hours){
        this.hours = hours;
    }
    public String getSpecificHours(int day){
        if (day < 0 || day > 3) {
            return "err";
        }else{
            return hours.get(day);
        }
    }
    public void editHours(int day, String time) {
        // day=0 corresponds to weekday open time
        // day=3 corresponds to weekend close time
        if (day < 0 || day > 3){
            return;
        }else{
            hours.set(day,time);
        }
    }

    public void addService(String service){
        services.add(service);
    }
    public List<String> getServices(){
        return this.services;
    }

    public List<String> getOpenRequests(){
        return openRequests;
    }
    public void setOpenRequests(List<String> openRequests){ this.openRequests = openRequests; }

}
