package com.jpoole.service_novigrad;


import java.util.ArrayList;

public class Service {
    private String id;    //The unique id generated by the DB
    private String name;  //the name of the service
    private double price;
    private int openRequestsCount;
    private int totalRequestsCount;

    private ArrayList<ServiceElement> serviceElements;


    public Service(){
        this.serviceElements = new ArrayList<ServiceElement>();
        this.name = "";
        this.id = "";
        this.price = 0;
    }

    public String getName(){
        return name;
    }
    public void setName(String name){
        this.name = name;
    }
    public double getPrice(){
        return price;
    }
    public void setPrice(double price){
        this.price = price;
    }
    public void setId(String id){
        this.id = id;
    }
    public String getId(){
        return id;
    }
    public ArrayList<ServiceElement> getServiceElements(){
        return serviceElements;
    }
    public void setServiceElements(ArrayList<ServiceElement> serviceElements){
        this.serviceElements = serviceElements;
    }
    public int getOpenRequestsCount(){
        return openRequestsCount;
    }
    public int getTotalRequestsCount(){
        return totalRequestsCount;
    }

}
